import { createRequestHandler, type ServerBuild } from 'react-router';

/*
 * Cloudflare Pages catch-all. React Router 7 dropped the Remix
 * `@remix-run/cloudflare-pages` `createPagesFunctionHandler` helper, so this
 * uses the framework-agnostic `createRequestHandler` from `react-router` and a
 * thin Pages adapter (Pages already hands us a WHATWG `Request`).
 *
 * NOTE: the primary production deploy is the Node server
 * (`react-router-serve ./build/server/index.js`, see Dockerfile). This CF
 * Pages entry is the secondary/legacy path; the `load-context` cloudflare
 * binding wiring should be reviewed before relying on it again.
 */
export const onRequest: PagesFunction = async (context) => {
  /*
   * Generated by `react-router build`; absent during plain `tsc --noEmit`.
   * @ts-ignore build output is created before Cloudflare Pages serves this function
   */
  const serverBuild = (await import('../build/server')) as unknown as ServerBuild;

  const handler = createRequestHandler(serverBuild, process.env.NODE_ENV);

  return handler(context.request, {
    cloudflare: { env: context.env },
  } as unknown as never);
};
