apiVersion: v1
kind: LimitRange
metadata:
  name: workspace-runtime-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.defaultRequest.memory | quote }}
      default:
        cpu: {{ .Values.limitRange.default.cpu | quote }}
        memory: {{ .Values.limitRange.default.memory | quote }}
      max:
        cpu: {{ .Values.limitRange.max.cpu | quote }}
        memory: {{ .Values.limitRange.max.memory | quote }}
