apiVersion: v1
kind: ResourceQuota
metadata:
  name: workspace-runtime-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: {{ .Values.resourceQuota.pods | quote }}
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentVolumeClaims | quote }}
