import { spawn, type ChildProcess } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { StringDecoder } from 'node:string_decoder';

/*
 * Real, persistent terminal sessions for the workspace agent.
 *
 * Each session owns a long-lived shell process, so working directory, exported
 * environment and shell history all persist across commands the way a real
 * terminal does. Sessions are addressable by id so a client that drops its
 * WebSocket can reattach to the same shell (with recent scrollback replayed)
 * instead of losing its state.
 *
 * Two backends:
 *  - node-pty (preferred): a true PTY. Interactive programs, line editing,
 *    echo, resize and Ctrl+C-as-SIGINT all work because the kernel pty + shell
 *    handle them. Loaded lazily and optionally — if the native module is not
 *    present the agent transparently falls back.
 *  - process-group shell (fallback): a piped shell spawned as its own process
 *    group so Ctrl+C can be delivered to the foreground command via SIGINT to
 *    the group. No pseudo-terminal, so there is no kernel echo/line-editing,
 *    but commands run, output streams, and cwd/env/history still persist.
 */

export interface TerminalBackend {
  write(data: string): void;
  resize(cols: number, rows: number): void;
  interrupt(): void;
  onData(listener: (chunk: string) => void): void;
  // Returns a disposer that REMOVES the listener. The /terminal endpoint registers
  // an onExit per WebSocket connection to a shared, long-lived session, so without
  // removal the listeners accumulate on every reattach (leak).
  onExit(listener: (exitCode: number) => void): () => void;
  kill(signal?: NodeJS.Signals): void;
  readonly mode: 'pty' | 'pipe';
}

export interface TerminalSpawnOptions {
  shell: string;
  cwd: string;
  env: NodeJS.ProcessEnv;
  cols: number;
  rows: number;
  /*
   * Emulate the WebContainer `jsh --osc` protocol over a real shell. The Bolt
   * client (app/utils/shell.ts) opens the terminal as `/bin/jsh --osc` and
   * blocks until the shell emits OSC 654 markers (`interactive`, `prompt`,
   * `exit=<code>`); the action-runner uses the same markers to detect when an
   * AI shell/start/build command has finished. A plain bash never emits them,
   * so without this the terminal and every AI shell action hang forever. When
   * enabled we drive an interactive bash through a generated rcfile that emits
   * the markers. The markers are stripped client-side, so they are invisible.
   */
  osc?: boolean;
}

// node-pty is an optional (native) dependency. Resolve it once; cache null on
// failure so we don't repeatedly pay the import cost when it isn't installed.
// The specifier is hidden behind an indirect import so the build doesn't fail
// when the module is absent — presence is a pure runtime concern.
const importOptional = new Function('specifier', 'return import(specifier)') as (specifier: string) => Promise<any>;

let ptyModulePromise: Promise<any | null> | undefined;

async function loadPtyModule(): Promise<any | null> {
  if (ptyModulePromise === undefined) {
    ptyModulePromise = importOptional('node-pty')
      .then((mod) => (mod as { default?: unknown }).default ?? mod)
      .catch(() => null);
  }

  return ptyModulePromise;
}

/*
 * rcfile that turns a real interactive bash into a jsh-OSC-protocol speaker:
 *  - emits `\e]654;interactive\a` once at startup (handshake complete),
 *  - emits `\e]654;prompt\a` on every prompt (via PS1, non-printing-wrapped),
 *  - emits `\e]654;exit=<code>:<code>\a` after every command (via PROMPT_COMMAND).
 * It still sources the system/user bashrc first so PATH and aliases are intact.
 */
const OSC_RCFILE_CONTENT = `# Generated by vibecore workspace-agent — jsh OSC 654 protocol emulation.
if [ -r /etc/profile ]; then . /etc/profile 2>/dev/null; fi
if [ -n "$HOME" ] && [ -r "$HOME/.bashrc" ]; then . "$HOME/.bashrc" 2>/dev/null; fi
__vibecore_osc_prompt() { local __code=$?; printf '\\033]654;exit=%s:%s\\007' "$__code" "$__code"; }
PROMPT_COMMAND='__vibecore_osc_prompt'
PS1='\\[\\033]654;prompt\\007\\]\\w \\$ '
printf '\\033]654;interactive\\007'
`;

let oscRcfilePath: string | undefined;

function ensureOscRcfile(): string {
  if (!oscRcfilePath) {
    /*
     * Write into a private per-agent temp dir (0700) with a fresh random name
     * rather than a fixed, world-predictable path in the shared temp dir. A
     * fixed name is a classic symlink/pre-creation target — sourcing an
     * attacker-controlled rc into every interactive shell. `wx` also fails hard
     * if the path somehow already exists instead of following a symlink.
     */
    const dir = mkdtempSync(join(tmpdir(), 'vibecore-osc-'));
    const path = join(dir, 'jsh-osc.bashrc');
    writeFileSync(path, OSC_RCFILE_CONTENT, { mode: 0o600, flag: 'wx' });
    oscRcfilePath = path;
  }

  return oscRcfilePath;
}

// The OSC protocol is bash-specific (PROMPT_COMMAND / PS1 escapes). If the
// configured shell is not bash, fall back to /bin/bash for the protocol.
function resolveSpawnSpec(options: TerminalSpawnOptions): { shell: string; args: string[] } {
  if (options.osc) {
    const bash = /(^|\/)bash$/.test(options.shell) ? options.shell : '/bin/bash';
    return { shell: bash, args: ['--noprofile', '--rcfile', ensureOscRcfile(), '-i'] };
  }

  return { shell: options.shell, args: [] };
}

function createPtyBackend(
  pty: any,
  options: TerminalSpawnOptions,
  spec: { shell: string; args: string[] },
): TerminalBackend {
  const proc = pty.spawn(spec.shell, spec.args, {
    name: 'xterm-256color',
    cols: options.cols,
    rows: options.rows,
    cwd: options.cwd,
    env: options.env,
  });

  return {
    mode: 'pty',
    write: (data) => proc.write(data),
    resize: (cols, rows) => {
      try {
        proc.resize(Math.max(1, cols), Math.max(1, rows));
      } catch {
        // resizing a dead pty throws; ignore.
      }
    },
    interrupt: () => proc.write('\x03'),
    onData: (listener) => proc.onData(listener),
    onExit: (listener) => {
      const disposable = proc.onExit((event: { exitCode: number }) => listener(event.exitCode ?? 0));

      return () => disposable.dispose();
    },
    kill: (signal) => {
      try {
        proc.kill(signal);
      } catch {
        // already gone
      }
    },
  };
}

function createPipeBackend(options: TerminalSpawnOptions, spec: { shell: string; args: string[] }): TerminalBackend {
  // `detached: true` makes the child a process-group leader so we can deliver a
  // signal to the whole group (the shell + whatever it is currently running).
  const child: ChildProcess = spawn(spec.shell, spec.args, {
    cwd: options.cwd,
    env: { ...options.env, COLUMNS: String(options.cols), LINES: String(options.rows) },
    detached: true,
    stdio: ['pipe', 'pipe', 'pipe'],
  });

  // Install a *caught* (no-op) SIGINT handler in the shell. A caught signal is
  // reset to its default disposition in exec'd children, so a Ctrl+C delivered
  // to the whole process group kills the foreground command (default action)
  // while the shell itself survives — the same end-result as a PTY's job
  // control, without a controlling terminal.
  const safeStdinWrite = (data: string) => {
    try {
      child.stdin?.write(data);
    } catch {
      // stdin closed (shell exited); drop the write instead of crashing.
    }
  };

  child.stdin?.on('error', () => {
    // Broken pipe after the shell exits — swallow so it isn't an unhandled stream error.
  });

  safeStdinWrite("trap ':' INT\n");

  const dataListeners: Array<(chunk: string) => void> = [];
  const exitListeners: Array<(exitCode: number) => void> = [];

  /*
   * Decode through a StringDecoder, not chunk.toString(): a multi-byte UTF-8
   * sequence (emoji/CJK/accented chars, common in dev-server output and CLI
   * spinners) that straddles a chunk boundary would otherwise be mangled into
   * replacement chars. StringDecoder buffers the incomplete tail across chunks.
   */
  const outputDecoder = new StringDecoder('utf8');

  const emit = (chunk: Buffer) => {
    const text = outputDecoder.write(chunk);

    if (!text) {
      return;
    }

    for (const listener of dataListeners) {
      listener(text);
    }
  };

  child.stdout?.on('data', emit);
  child.stderr?.on('data', emit);
  // Guard pipe Readables: an unhandled 'error' on stdout/stderr crashes the agent and every session.
  child.stdout?.on('error', () => {});
  child.stderr?.on('error', () => {});
  child.on('exit', (code) => {
    for (const listener of exitListeners) {
      listener(code ?? 0);
    }
  });

  /*
   * A failed spawn (ENOENT for a missing shell, EACCES, …) emits 'error' with no
   * matching 'exit'. With no listener Node turns this into an uncaught exception
   * that crashes the whole agent. Surface it as a non-zero exit so the session is
   * cleaned up instead.
   */
  child.on('error', () => {
    for (const listener of exitListeners) {
      listener(1);
    }
  });

  const signalGroup = (signal: NodeJS.Signals) => {
    if (child.pid === undefined) {
      return;
    }

    const pid = child.pid;

    try {
      // Negative pid → the process group.
      process.kill(-pid, signal);
    } catch {
      try {
        child.kill(signal);
      } catch {
        // already gone
      }
    }

    // Escalate to SIGKILL if a trapped/wedged foreground command ignores a
    // terminating signal, so a disposed session can't leak an orphan process
    // group that permanently holds a per-workspace process slot.
    if (signal === 'SIGTERM' || signal === 'SIGQUIT' || signal === 'SIGHUP') {
      const escalate = setTimeout(() => {
        if (child.exitCode !== null || child.signalCode !== null) {
          return;
        }

        try {
          process.kill(-pid, 'SIGKILL');
        } catch {
          try {
            child.kill('SIGKILL');
          } catch {
            // already gone
          }
        }
      }, 5_000);

      if (typeof escalate.unref === 'function') {
        escalate.unref();
      }
    }
  };

  return {
    mode: 'pipe',
    write: (data) => {
      safeStdinWrite(data);
    },
    resize: (cols, rows) => {
      // No pty to resize; keep COLUMNS/LINES roughly informative for new
      // children by exporting through the shell.
      safeStdinWrite(`export COLUMNS=${Math.max(1, cols)} LINES=${Math.max(1, rows)}\n`);
    },
    interrupt: () => signalGroup('SIGINT'),
    onData: (listener) => {
      dataListeners.push(listener);
    },
    onExit: (listener) => {
      exitListeners.push(listener);

      return () => {
        const idx = exitListeners.indexOf(listener);

        if (idx !== -1) {
          exitListeners.splice(idx, 1);
        }
      };
    },
    kill: (signal = 'SIGTERM') => signalGroup(signal),
  };
}

export async function createTerminalBackend(options: TerminalSpawnOptions): Promise<TerminalBackend> {
  const spec = resolveSpawnSpec(options);
  const pty = await loadPtyModule();

  if (pty && typeof pty.spawn === 'function') {
    try {
      return createPtyBackend(pty, options, spec);
    } catch {
      // fall through to the pipe backend on any spawn failure
    }
  }

  return createPipeBackend(options, spec);
}

export interface TerminalSession {
  readonly id: string;
  readonly backend: TerminalBackend;
  /** Recent output kept so a reattaching client can repaint its screen. */
  scrollback(): string;
  attach(listener: (chunk: string) => void): () => void;
  write(data: string): void;
  resize(cols: number, rows: number): void;
  interrupt(): void;
  dispose(signal?: NodeJS.Signals): void;
}

export interface TerminalSessionManagerOptions {
  shell?: string;
  cwd: string;
  env?: NodeJS.ProcessEnv;
  /** Max bytes of scrollback retained per session. */
  scrollbackBytes?: number;
  /** How long a detached session stays alive awaiting reattach. */
  reattachGraceMs?: number;
  maxSessions?: number;
  /** Emulate the jsh OSC 654 protocol so the Bolt client handshake works. */
  osc?: boolean;
}

/*
 * Owns the live sessions for one workspace agent. Sessions survive a client
 * disconnect for `reattachGraceMs` so a flaky network doesn't kill the user's
 * shell; an explicit kill or the grace timeout disposes it.
 */
export class TerminalSessionManager {
  private readonly sessions = new Map<string, InternalSession>();
  // In-flight creations keyed by id, so concurrent getOrCreate(id) calls dedupe
  // on one backend instead of racing the `await createTerminalBackend` and
  // orphaning a shell process (TOCTOU between the existing-check and registration).
  private readonly pending = new Map<string, Promise<TerminalSession>>();
  private readonly shell: string;
  private readonly cwd: string;
  private readonly env: NodeJS.ProcessEnv;
  private readonly scrollbackBytes: number;
  private readonly reattachGraceMs: number;
  private readonly maxSessions: number;
  private readonly osc: boolean;

  constructor(options: TerminalSessionManagerOptions) {
    this.shell = options.shell ?? process.env.SHELL ?? '/bin/bash';
    this.cwd = options.cwd;
    this.env = options.env ?? process.env;
    this.scrollbackBytes = options.scrollbackBytes ?? 256 * 1024;
    this.reattachGraceMs = options.reattachGraceMs ?? 5 * 60 * 1000;
    this.maxSessions = options.maxSessions ?? 16;
    this.osc = options.osc ?? false;
  }

  get size() {
    return this.sessions.size;
  }

  has(id: string) {
    return this.sessions.has(id);
  }

  async getOrCreate(id: string, spawn: { cols?: number; rows?: number } = {}): Promise<TerminalSession> {
    const existing = this.sessions.get(id);

    if (existing) {
      if (existing.disposeTimer) {
        clearTimeout(existing.disposeTimer);
        existing.disposeTimer = undefined;
      }

      return existing.handle;
    }

    // Dedupe concurrent creations of the same id on a single in-flight promise.
    const inflight = this.pending.get(id);

    if (inflight) {
      return inflight;
    }

    /*
     * Reserve a slot against BOTH live sessions AND in-flight creations, atomically
     * with the pending.set below (no await between). #create's own size check ran
     * before its first await and ignored pending, so N concurrent distinct-id
     * creations each passed a stale size check and blew past maxSessions. The
     * .finally(pending.delete) rolls the reservation back if creation rejects.
     */
    if (this.sessions.size + this.pending.size >= this.maxSessions) {
      throw new Error('Too many terminal sessions');
    }

    const creation = this.#create(id, spawn).finally(() => {
      this.pending.delete(id);
    });
    this.pending.set(id, creation);

    return creation;
  }

  async #create(id: string, spawn: { cols?: number; rows?: number }): Promise<TerminalSession> {
    if (this.sessions.size >= this.maxSessions) {
      throw new Error('Too many terminal sessions');
    }

    const backend = await createTerminalBackend({
      shell: this.shell,
      cwd: this.cwd,
      env: this.env,
      cols: spawn.cols ?? 80,
      rows: spawn.rows ?? 24,
      osc: this.osc,
    });

    const internal: InternalSession = {
      listeners: new Set(),
      buffer: '',
      disposeTimer: undefined,
      handle: undefined as unknown as TerminalSession,
    };

    backend.onData((chunk) => {
      internal.buffer = (internal.buffer + chunk).slice(-this.scrollbackBytes);

      for (const listener of internal.listeners) {
        listener(chunk);
      }
    });

    backend.onExit(() => {
      /*
       * Only clear the map if it still points to THIS session. dispose(id)
       * removes the entry then kills the backend asynchronously, so this exit can
       * fire AFTER a new getOrCreate(id) recreated a fresh session under the same
       * id — deleting it here would silently drop the live session.
       */
      if (this.sessions.get(id) === internal) {
        this.sessions.delete(id);
      }
    });

    const handle: TerminalSession = {
      id,
      backend,
      scrollback: () => internal.buffer,
      attach: (listener) => {
        internal.listeners.add(listener);

        /*
         * A viewer (re)attached — cancel any pending dispose armed when the last
         * viewer left (or by a concurrent getOrCreate). Without this the grace-window
         * timer keeps running and disposes the shell out from under an actively
         * attached client.
         */
        if (internal.disposeTimer) {
          clearTimeout(internal.disposeTimer);
          internal.disposeTimer = undefined;
        }

        return () => {
          internal.listeners.delete(listener);

          // Last viewer left: keep the shell alive briefly for reattach.
          if (internal.listeners.size === 0 && !internal.disposeTimer) {
            internal.disposeTimer = setTimeout(() => {
              this.dispose(id);
            }, this.reattachGraceMs);

            if (typeof internal.disposeTimer.unref === 'function') {
              internal.disposeTimer.unref();
            }
          }
        };
      },
      write: (data) => backend.write(data),
      resize: (cols, rows) => backend.resize(cols, rows),
      interrupt: () => backend.interrupt(),
      dispose: (signal) => this.dispose(id, signal),
    };

    internal.handle = handle;
    this.sessions.set(id, internal);

    return handle;
  }

  dispose(id: string, signal: NodeJS.Signals = 'SIGTERM') {
    const internal = this.sessions.get(id);

    if (!internal) {
      return;
    }

    if (internal.disposeTimer) {
      clearTimeout(internal.disposeTimer);
    }

    this.sessions.delete(id);
    internal.handle.backend.kill(signal);
  }

  disposeAll() {
    for (const id of [...this.sessions.keys()]) {
      this.dispose(id);
    }
  }
}

interface InternalSession {
  listeners: Set<(chunk: string) => void>;
  buffer: string;
  disposeTimer: ReturnType<typeof setTimeout> | undefined;
  handle: TerminalSession;
}
