import type { GalleryDemoAppSummary } from './types.js';

const ECODE_AUTHOR = Object.freeze({
  id: 'ecode-studio',
  displayName: 'E-Code Studio',
  handle: 'ecode',
  verified: true,
});

const app = (value: Omit<GalleryDemoAppSummary, 'author' | 'thumbnailUrl' | 'previewUrl'>): GalleryDemoAppSummary =>
  Object.freeze({
    ...value,
    author: ECODE_AUTHOR,
    technologies: Object.freeze([...value.technologies]),
    thumbnailUrl: `/gallery-apps/${value.id}/thumbnail.png`,
    previewUrl: `/gallery-apps/${value.id}/preview/`,
  });

/** Working applications published to seed the remix Gallery. Every app is proven install→start→HTTP 200→DOM before listing. */
export const GALLERY_DEMO_APP_SUMMARIES = Object.freeze([
  app({
    id: 'vendor-risk-review',
    key: 'demo-vendor-risk-review',
    slug: 'vendor-risk-review',
    name: 'Vendor Risk Review',
    description:
      'Every new vendor is a risk nobody has time to assess. Score them in five minutes, route approval to the right level, and pull the audit trail the day the regulator asks for it.',
    artifactType: 'business-app',
    category: 'compliance',
    technologies: ['React', 'TypeScript', 'Express', 'SQLite', 'Vite'],
    publishedAt: '2026-07-17T09:00:00.000Z',
    remixCount: 96,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'field-service-inspector',
    key: 'demo-field-service-inspector',
    slug: 'field-service-inspector',
    name: 'Field Service Inspector',
    description:
      'Your technicians work where there is no signal. Inspections, photos, customer signature: everything works offline and syncs the moment the 4G comes back.',
    artifactType: 'mobile-app',
    category: 'field-service',
    technologies: ['Expo', 'React Native', 'TypeScript', 'Metro'],
    publishedAt: '2026-07-17T08:30:00.000Z',
    remixCount: 74,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'revenue-cohort-explorer',
    key: 'demo-revenue-cohort-explorer',
    slug: 'revenue-cohort-explorer',
    name: 'Revenue Cohort Explorer',
    description:
      'You know what you invoice. Do you know which cohort is still making you money eighteen months later? Click through the chart all the way down to the customer.',
    artifactType: 'data-viz',
    category: 'analytics',
    technologies: ['React', 'TypeScript', 'Vite', 'SVG'],
    publishedAt: '2026-07-16T17:45:00.000Z',
    remixCount: 61,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'qbr-generator',
    key: 'demo-qbr-generator',
    slug: 'qbr-generator',
    name: 'QBR Generator',
    description:
      'The quarterly business review, generated from your real numbers instead of being retyped by hand the night before. Two artifacts — the deck and the data appendix — share one backend.',
    artifactType: 'slide-deck',
    category: 'reporting',
    technologies: ['React', 'TypeScript', 'Express', 'Vite'],
    publishedAt: '2026-07-16T15:20:00.000Z',
    remixCount: 43,
    featured: false,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'incident-postmortem-explainer',
    key: 'demo-incident-postmortem-explainer',
    slug: 'incident-postmortem-explainer',
    name: 'Incident Postmortem Explainer',
    description:
      'An incident explained in thirty animated seconds instead of twelve pages nobody reads. Scrub the timeline, replay each phase, share the story.',
    artifactType: 'animation',
    category: 'incident-response',
    technologies: ['React', 'TypeScript', 'Vite', 'Web Animations'],
    publishedAt: '2026-07-15T14:10:00.000Z',
    remixCount: 38,
    featured: false,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'warehouse-layout-planner',
    key: 'demo-warehouse-layout-planner',
    slug: 'warehouse-layout-planner',
    name: 'Warehouse Layout Planner',
    description:
      'Move an aisle and see immediately what you gain in capacity — before moving a single pallet. A live 3D model of your floor with real rack math.',
    artifactType: 'three-d',
    category: 'logistics',
    technologies: ['Three.js', 'React', 'TypeScript', 'Vite'],
    publishedAt: '2026-07-15T11:00:00.000Z',
    remixCount: 52,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'pipeline-crm',
    key: 'demo-pipeline-crm',
    slug: 'pipeline-crm',
    name: 'Pipeline CRM',
    description:
      'The CRM your team will actually use: accounts, contacts, opportunities and forecasts. Without the six-month integration project or the per-seat invoice.',
    artifactType: 'crm',
    category: 'sales',
    technologies: ['React', 'TypeScript', 'Vite'],
    publishedAt: '2026-07-14T16:40:00.000Z',
    remixCount: 87,
    featured: false,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'storefront',
    key: 'demo-storefront',
    slug: 'storefront',
    name: 'Storefront',
    description:
      'Catalog, cart, Stripe checkout, orders, inventory and a back office. A store that takes real test-mode payments — not a mockup.',
    artifactType: 'ecommerce',
    category: 'commerce',
    technologies: ['React', 'TypeScript', 'Express', 'Stripe', 'SQLite', 'Vite'],
    publishedAt: '2026-07-14T10:15:00.000Z',
    remixCount: 69,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'react-saas',
    key: 'demo-react-saas-crm',
    slug: 'orbit-crm',
    name: 'Orbit CRM',
    description: 'A working sales workspace for contacts, pipeline stages, follow-ups and revenue visibility.',
    artifactType: 'business-app',
    category: 'sales',
    technologies: ['React', 'Vite', 'TypeScript'],
    publishedAt: '2026-07-10T09:00:00.000Z',
    remixCount: 428,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'next-dashboard',
    key: 'demo-next-operations-dashboard',
    slug: 'northstar-operations',
    name: 'Northstar Operations',
    description: 'An incident and service operations dashboard with live health, ownership and resolution workflows.',
    artifactType: 'dashboard',
    category: 'operations',
    technologies: ['Next.js', 'React', 'TypeScript'],
    publishedAt: '2026-07-09T14:30:00.000Z',
    remixCount: 316,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'fastify-api',
    key: 'demo-fastify-api-monitor',
    slug: 'pulse-api-monitor',
    name: 'Pulse API Monitor',
    description: 'A self-contained API monitoring tool that runs endpoint checks and surfaces latency and failures.',
    artifactType: 'developer-tool',
    category: 'developer-tools',
    technologies: ['Fastify', 'Node.js', 'TypeScript'],
    publishedAt: '2026-07-08T11:15:00.000Z',
    remixCount: 207,
    featured: false,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'ai-agent',
    key: 'demo-ai-launch-planner',
    slug: 'launchline-planner',
    name: 'Launchline Planner',
    description: 'A collaborative launch planner that turns milestones into a focused, executable release checklist.',
    artifactType: 'productivity-app',
    category: 'productivity',
    technologies: ['React', 'Vite', 'TypeScript'],
    publishedAt: '2026-07-07T16:45:00.000Z',
    remixCount: 265,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'landing-page',
    key: 'demo-booking-customer-app',
    slug: 'kindred-booking',
    name: 'Kindred Booking',
    description: 'A customer booking experience with real time-slot selection, contact capture and confirmation.',
    artifactType: 'customer-app',
    category: 'booking',
    technologies: ['Vite', 'JavaScript', 'CSS'],
    publishedAt: '2026-07-06T10:20:00.000Z',
    remixCount: 391,
    featured: true,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
  app({
    id: 'mobile-starter',
    key: 'demo-field-service-pwa',
    slug: 'relay-field-service',
    name: 'Relay Field Service',
    description: 'An installable field-service PWA for daily jobs, technician notes and offline-ready status updates.',
    artifactType: 'pwa',
    category: 'field-service',
    technologies: ['React', 'Vite', 'TypeScript', 'PWA'],
    publishedAt: '2026-07-05T08:10:00.000Z',
    remixCount: 184,
    featured: false,
    remixAllowed: true,
    moderationStatus: 'approved',
  }),
] satisfies readonly GalleryDemoAppSummary[]);

const summariesByKey = new Map<string, GalleryDemoAppSummary>();
for (const item of GALLERY_DEMO_APP_SUMMARIES) {
  summariesByKey.set(item.id, item);
  summariesByKey.set(item.key, item);
  summariesByKey.set(item.slug, item);
}

export function listGalleryDemoAppSummaries(): readonly GalleryDemoAppSummary[] {
  return GALLERY_DEMO_APP_SUMMARIES;
}

export function getGalleryDemoAppSummary(idKeyOrSlug: string): GalleryDemoAppSummary | undefined {
  return summariesByKey.get(idKeyOrSlug.trim().toLowerCase());
}
