apiVersion: v1
kind: ResourceQuota
metadata:
  name: workspace-runtime-quota
  namespace: workspaces
spec:
  hard:
    pods: "500"
    requests.cpu: "250"
    requests.memory: 500Gi
    limits.cpu: "1000"
    limits.memory: 2Ti
    persistentvolumeclaims: "500"
