export type AuthScaffoldLocale = 'en' | 'fr';

export type AuthScaffoldCopy = Readonly<{
  htmlLang: AuthScaffoldLocale;
  migrationHeader: string;
  loginTitle: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  loginAction: string;
  signupAction: string;
  requestFailed: string;
  emailPasswordRequired: string;
  emailAlreadyRegistered: string;
  signupFailed: string;
  invalidCredentials: string;
  notAuthenticated: string;
  invalidSession: string;
  readme: string;
}>;

const COPY: Readonly<Record<AuthScaffoldLocale, AuthScaffoldCopy>> = {
  en: {
    htmlLang: 'en',
    migrationHeader: 'Auth scaffold: end-user accounts for this app (E-Code "Add Authentication").',
    loginTitle: 'Sign in',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    loginAction: 'Log in',
    signupAction: 'Sign up',
    requestFailed: 'The request failed.',
    emailPasswordRequired: 'Email and password are required.',
    emailAlreadyRegistered: 'This email address is already registered.',
    signupFailed: 'Sign-up failed.',
    invalidCredentials: 'The email address or password is invalid.',
    notAuthenticated: 'Authentication is required.',
    invalidSession: 'The session is invalid or has expired.',
    readme: `# Authentication (generated by E-Code "Add Authentication")

Real email/password authentication backed by this project's Postgres (\`DATABASE_URL\`).

## 1. Install dependencies
\`\`\`
npm i pg bcryptjs jsonwebtoken cookie-parser
\`\`\`

## 2. Run the migration
\`\`\`
psql "$DATABASE_URL" -f db/migrations/0001_create_users.sql
\`\`\`

## 3. Mount the router (Express)
\`\`\`js
const cookieParser = require('cookie-parser');
const auth = require('./auth');

app.use(cookieParser());
app.use(auth.router); // POST /auth/signup, /auth/login, /auth/logout; GET /auth/me

// Protect a route:
app.get('/private', auth.requireAuth, (req, res) => res.json({ user: req.user }));

// Serve the login page:
app.get('/login', (req, res) => res.sendFile(__dirname + '/auth/login.html'));
\`\`\`

## Environment variables
- \`AUTH_JWT_SECRET\` — set automatically by the scaffold (signs the session JWT).
- \`AUTH_SESSION_COOKIE\` — optional cookie name (default: \`ecode_session\`).

Sessions use httpOnly JWT cookies with a seven-day expiry. If the app does not use Express,
port the router to its framework; the Postgres queries and JWT helpers remain unchanged.
`,
  },
  fr: {
    htmlLang: 'fr',
    migrationHeader:
      'Authentification : comptes des utilisateurs finaux de cette application (E-Code « Ajouter l’authentification »).',
    loginTitle: 'Connexion',
    emailPlaceholder: 'Adresse e-mail',
    passwordPlaceholder: 'Mot de passe',
    loginAction: 'Se connecter',
    signupAction: 'S’inscrire',
    requestFailed: 'La requête a échoué.',
    emailPasswordRequired: 'L’adresse e-mail et le mot de passe sont obligatoires.',
    emailAlreadyRegistered: 'Cette adresse e-mail est déjà enregistrée.',
    signupFailed: 'L’inscription a échoué.',
    invalidCredentials: 'L’adresse e-mail ou le mot de passe est incorrect.',
    notAuthenticated: 'Vous devez vous authentifier.',
    invalidSession: 'La session est invalide ou a expiré.',
    readme: `# Authentification (générée par E-Code « Ajouter l’authentification »)

Authentification réelle par adresse e-mail et mot de passe, adossée à la base Postgres du projet (\`DATABASE_URL\`).

## 1. Installer les dépendances
\`\`\`
npm i pg bcryptjs jsonwebtoken cookie-parser
\`\`\`

## 2. Exécuter la migration
\`\`\`
psql "$DATABASE_URL" -f db/migrations/0001_create_users.sql
\`\`\`

## 3. Monter le routeur (Express)
\`\`\`js
const cookieParser = require('cookie-parser');
const auth = require('./auth');

app.use(cookieParser());
app.use(auth.router); // POST /auth/signup, /auth/login, /auth/logout; GET /auth/me

// Protéger une route :
app.get('/private', auth.requireAuth, (req, res) => res.json({ user: req.user }));

// Servir la page de connexion :
app.get('/login', (req, res) => res.sendFile(__dirname + '/auth/login.html'));
\`\`\`

## Variables d’environnement
- \`AUTH_JWT_SECRET\` — définie automatiquement par le scaffold (signe le JWT de session).
- \`AUTH_SESSION_COOKIE\` — nom facultatif du cookie (valeur par défaut : \`ecode_session\`).

Les sessions utilisent des cookies JWT httpOnly qui expirent après sept jours. Si l’application n’utilise pas Express,
adaptez le routeur à son framework ; les requêtes Postgres et les utilitaires JWT restent inchangés.
`,
  },
};

export function normalizeAuthScaffoldLocale(locale?: string | null): AuthScaffoldLocale {
  return locale?.trim().toLowerCase().split(/[-_]/)[0] === 'fr' ? 'fr' : 'en';
}

export function getAuthScaffoldCopy(locale?: string | null): AuthScaffoldCopy {
  return COPY[normalizeAuthScaffoldLocale(locale)];
}
