import { randomBytes } from 'node:crypto';
import { getAuthScaffoldCopy } from './auth-scaffold.copy.js';

/*
 * "Add Authentication" scaffold (Replit-Auth-equivalent for the GENERATED app).
 * Writes REAL, runnable email/password auth files into the project, backed by
 * the project's own Postgres (DATABASE_URL): a users-table migration, an Express
 * router with session/JWT middleware (signup/login/logout/me), a login page and
 * a README with the one-line wiring. Idempotent — the caller skips files that
 * already exist. Gated behind AUTH_SCAFFOLD_ENABLED so it ships dormant.
 *
 * Zero mock: the emitted code runs as-is on an Express app once mounted and the
 * migration is applied (`npm i pg bcryptjs jsonwebtoken cookie-parser`).
 */

export function isAuthScaffoldEnabled(): boolean {
  return process.env.AUTH_SCAFFOLD_ENABLED === 'true';
}

/** A fresh 48-byte URL-safe secret for signing the session JWT. */
export function generateAuthJwtSecret(): string {
  return randomBytes(48).toString('base64url');
}

function usersMigrationSql(locale?: string | null): string {
  const copy = getAuthScaffoldCopy(locale);

  return `-- ${copy.migrationHeader}
CREATE TABLE IF NOT EXISTS users (
  id            BIGSERIAL PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
`;
}

function authIndexJs(locale?: string | null): string {
  const copy = getAuthScaffoldCopy(locale);

  return `'use strict';
/**
 * Drop-in email/password authentication for an Express app, backed by the
 * project's Postgres (DATABASE_URL). Generated by E-Code "Add Authentication".
 *
 * Wiring (see auth/README.md):
 *   const cookieParser = require('cookie-parser');
 *   const auth = require('./auth');
 *   app.use(cookieParser());
 *   app.use(auth.router);                       // /auth/signup /auth/login /auth/logout /auth/me
 *   app.get('/private', auth.requireAuth, (req, res) => res.json({ user: req.user }));
 */
const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { Pool } = require('pg');

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const JWT_SECRET = process.env.AUTH_JWT_SECRET || 'set-AUTH_JWT_SECRET-in-env';
const COOKIE = process.env.AUTH_SESSION_COOKIE || 'ecode_session';

const router = express.Router();
router.use(express.json());

function setSession(res, user) {
  const token = jwt.sign({ sub: String(user.id), email: user.email }, JWT_SECRET, { expiresIn: '7d' });
  res.cookie(COOKIE, token, {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    maxAge: 7 * 24 * 3600 * 1000,
  });
}

router.post('/auth/signup', async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) return res.status(400).json({ error: '${copy.emailPasswordRequired}' });
  try {
    const hash = await bcrypt.hash(password, 10);
    const { rows } = await pool.query(
      'INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id, email',
      [String(email).toLowerCase(), hash],
    );
    setSession(res, rows[0]);
    res.json({ user: rows[0] });
  } catch (e) {
    if (e && e.code === '23505') return res.status(409).json({ error: '${copy.emailAlreadyRegistered}' });
    res.status(500).json({ error: '${copy.signupFailed}' });
  }
});

router.post('/auth/login', async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) return res.status(400).json({ error: '${copy.emailPasswordRequired}' });
  const { rows } = await pool.query('SELECT id, email, password_hash FROM users WHERE email = $1', [
    String(email).toLowerCase(),
  ]);
  const user = rows[0];
  if (!user || !(await bcrypt.compare(password, user.password_hash))) {
    return res.status(401).json({ error: '${copy.invalidCredentials}' });
  }
  setSession(res, user);
  res.json({ user: { id: user.id, email: user.email } });
});

router.post('/auth/logout', (req, res) => {
  res.clearCookie(COOKIE);
  res.json({ ok: true });
});

function requireAuth(req, res, next) {
  const token = req.cookies && req.cookies[COOKIE];
  if (!token) return res.status(401).json({ error: '${copy.notAuthenticated}' });
  try {
    req.user = jwt.verify(token, JWT_SECRET);
    next();
  } catch {
    res.status(401).json({ error: '${copy.invalidSession}' });
  }
}

router.get('/auth/me', requireAuth, (req, res) => res.json({ user: { id: req.user.sub, email: req.user.email } }));

module.exports = { router, requireAuth, pool };
`;
}

function loginHtml(locale?: string | null): string {
  const copy = getAuthScaffoldCopy(locale);

  return `<!doctype html>
<html lang="${copy.htmlLang}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${copy.loginTitle}</title>
    <style>
      body { font-family: system-ui, sans-serif; display: grid; place-items: center; min-height: 100vh; margin: 0; }
      form { display: grid; gap: 10px; width: 280px; padding: 24px; border: 1px solid #ddd; border-radius: 10px; }
      input, button { padding: 10px; font-size: 14px; border-radius: 6px; border: 1px solid #ccc; }
      button { cursor: pointer; border: 0; background: #f26207; color: #fff; }
      .row { display: flex; gap: 8px; }
      .row button { flex: 1; }
      #msg { font-size: 13px; color: #b00; min-height: 18px; }
    </style>
  </head>
  <body>
    <form id="f">
      <h2 style="margin:0">${copy.loginTitle}</h2>
      <input id="email" type="email" placeholder="${copy.emailPlaceholder}" autocomplete="email" required />
      <input id="password" type="password" placeholder="${copy.passwordPlaceholder}" autocomplete="current-password" required />
      <div class="row">
        <button type="submit" data-action="/auth/login">${copy.loginAction}</button>
        <button type="submit" data-action="/auth/signup">${copy.signupAction}</button>
      </div>
      <div id="msg"></div>
    </form>
    <script>
      const f = document.getElementById('f');
      let action = '/auth/login';
      f.querySelectorAll('button').forEach((b) => b.addEventListener('click', () => (action = b.dataset.action)));
      f.addEventListener('submit', async (e) => {
        e.preventDefault();
        const msg = document.getElementById('msg');
        msg.textContent = '';
        const res = await fetch(action, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            email: document.getElementById('email').value,
            password: document.getElementById('password').value,
          }),
        });
        const data = await res.json().catch(() => ({}));
        if (res.ok) location.href = '/';
        else msg.textContent = data.error || '${copy.requestFailed}';
      });
    </script>
  </body>
</html>
`;
}

/** The real files the scaffold writes (relative project paths). */
export function generateAuthScaffoldFiles(locale: string = 'en'): Array<{ path: string; content: string }> {
  const copy = getAuthScaffoldCopy(locale);

  return [
    { path: 'db/migrations/0001_create_users.sql', content: usersMigrationSql(locale) },
    { path: 'auth/index.js', content: authIndexJs(locale) },
    { path: 'auth/login.html', content: loginHtml(locale) },
    { path: 'auth/README.md', content: copy.readme },
  ];
}
